version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - echo $(ifconfig | grep -v 169.254 | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p') $(cat /etc/hostname) >> /etc/hosts
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - TIMESTAMP_TAG="$(date -d @$((${CODEBUILD_START_TIME}/1000)) +'%Y-%m-%dT%HH%M')" #milis -> secs; Tag: [a-zA-Z0-9-_.]+
      - TAG="${CODEBUILD_RESOLVED_SOURCE_VERSION}"
      - IMAGE_URI_VERSION="${REPOSITORY_URI}:${TAG}"
      - echo ${IMAGE_URI_VERSION}
      - IMAGE_URI_LATEST="${REPOSITORY_URI}:test"
      - IMAGE_URI_TIMESTAMP="${REPOSITORY_URI}:test-${TIMESTAMP_TAG}"
  build:
    commands:
      - echo Entered the build phase...
      - docker login -u datatrackalex -p ${DOCKER_AUTH_PASSWORD}
      - docker build -f DockerfileAggregate -t alex-datatrack:${TAG} .

  post_build:
    commands:
      - echo Entered the post_build phase...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin ${REPOSITORY_BASE_URI}
      - docker tag alex-datatrack:${TAG} ${IMAGE_URI_VERSION}
      - docker tag alex-datatrack:${TAG} ${IMAGE_URI_TIMESTAMP}
      - docker tag alex-datatrack:${TAG} ${IMAGE_URI_LATEST}
      - docker push "$IMAGE_URI_VERSION"
      - docker push "$IMAGE_URI_TIMESTAMP"
      - docker push "$IMAGE_URI_LATEST"